########################################################################################################################
################################################# grid configuration ###################################################
########################################################################################################################

grids:
  electricity:
    powerflow: dc                       # powerflow

    active: True                        # grid active

    method: topology                    # grid creation method
                                        # options:
                                        #   - file: create grid from 'electricity.xlsx'
                                        #   - topology: create scenario first, then user has to assign agent-id to bus
                                        #     in 'topology.xlsx' file
                                        # TODO: Create automatic grid generator, e.g. based on Kerber grids

    file:
      file: electricity.xlsx            # file that contains the grid information
                                        # file types: xlsx
                                        # note: needs to be in the same folder as this file
    topology:
      file: topology.xlsx

    variable_grid_fees:
      active: False

      horizon: 86400                    # variable grid fees calculation horizon
                                        # unit: s

      update: 3600                      # variable grid fees update frequency
                                        # unit: s

    direct_power_control:
      active: False

      control: individual               # types of direct power control
                                        # individual: control individual devices
                                        # ems: control via EMS

      max_iteration: 10                 # maximal number of iteration

  heat:
    active: False

  hydrogen:
    active: False